//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alma_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
