//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alma_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioCarga { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<int> IdPerfil { get; set; }
    }
}
