//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alma_Reporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Usuario { get; set; }
        public byte[] Salt { get; set; }
        public byte[] Password { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string IdOperacion { get; set; }
        public string TelContacto { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public Nullable<int> IdArea { get; set; }
    }
}
